name: CI

on:
  push:
    branches:
      - feature/lab2
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build  

      - name: Run tests
        run: ./gradlew test  
